name: 'Terraform'
 
on:
  push:
    branches:
    - master
  
  workflow_dispatch:
 
jobs:
  terraform:
    
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      
    runs-on: ubuntu-latest
    # environment: production
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    steps:
    #Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2            
      
    - name: HashiCorp - Setup Terraform
  # You may pin to the exact commit or the version.
  # uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Terraform init
      run: terraform init

    - name: Terraform plan
   
       
      run: terraform plan 

    # - name: Terraform apply
    #   run: terraform apply -input=false -auto-approve

  apply:
    name: 'Apply'
    runs-on: ubuntu-latest
    needs: terraform
    environment:
        name: Dev
        # As prod-env required reviewers is `dineshba`,
        # it will wait for approval from dineshba
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}   

    steps:
    #... checkout, setup, init terraform steps like plan
    - name: Terraform Apply
      run: terraform apply -auto-approve
    
